sudo: false
language: python
python:
  - "pypy"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* || $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install PyDNS; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* || $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then pip install Py3DNS; fi
  - pip install .
  - pip install nose coverage
script:
  - nosetests --with-coverage --cover-package=validate_email
  - coverage report -m
after_success:
  - pip install coveralls
  - coveralls
matrix:
  allow_failures:
    - python: "nightly"
